#!/usr/bin/env bash
# AI Memory OS — first-time production deploy (Docker Compose mode)
#
# Idempotent. Run on the server, in the project root. The script:
#   1. checks prerequisites (docker, docker compose v2, openssl/python3)
#   2. interactively collects the required secrets if .env is missing
#   3. writes .env with strong defaults
#   4. brings up the full stack via docker compose -f docker-compose.yml -f docker-compose.prod.yml
#   5. waits for /health to return 200 and prints the next steps

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "========================================"
echo " AI Memory OS — Production Deploy"
echo " Root: $ROOT"
echo "========================================"

# ---- 1. preflight ----------------------------------------------------------
echo "[1/5] Preflight"
command -v docker >/dev/null || { echo "  ERROR: docker not installed"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "  ERROR: docker compose v2 not installed"; exit 1; }
command -v openssl >/dev/null || command -v python3 >/dev/null \
  || { echo "  ERROR: need openssl or python3 to generate secrets"; exit 1; }
echo "  docker $(docker --version | awk '{print $3}' | tr -d ,) OK"

# ---- 2. collect secrets (only on first run) --------------------------------
echo "[2/5] Configuration"
if [[ -f .env ]]; then
  echo "  .env already exists — reusing it. Delete to re-run setup."
else
  echo "  No .env found. Generating one."
  read -rp "  Public domain (e.g. memory.example.com, leave empty for IP-only access): " DOMAIN || true
  read -rsp "  PostgreSQL password (input hidden): " PG_PW && echo
  read -rsp "  Neo4j password (input hidden, leave empty to reuse PG password): " NEO4J_PW && echo
  read -rsp "  MinIO root password (input hidden, leave empty to reuse PG password): " MINIO_PW && echo
  read -rsp "  Grafana admin password (input hidden, leave empty to reuse PG password): " GF_PW && echo
  NEO4J_PW=${NEO4J_PW:-$PG_PW}
  MINIO_PW=${MINIO_PW:-$PG_PW}
  GF_PW=${GF_PW:-$PG_PW}

  gen_b64() {
    if command -v openssl >/dev/null; then
      openssl rand -base64 32 | tr -d '\n'
    else
      python3 -c "import os,base64;print(base64.b64encode(os.urandom(32)).decode())"
    fi
  }
  gen_hex() {
    if command -v openssl >/dev/null; then
      openssl rand -hex 32
    else
      python3 -c "import secrets;print(secrets.token_hex(32))"
    fi
  }

  MASTER_KEY="$(gen_b64)"
  JWT_SECRET="$(gen_hex)"

  cat > .env <<EOF
# Generated by scripts/deploy-prod.sh on $(date -u +%FT%TZ)
POSTGRES_USER=memoryos
POSTGRES_PASSWORD=$PG_PW
POSTGRES_DB=memory_os

NEO4J_PASSWORD=$NEO4J_PW

MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=$MINIO_PW

GRAFANA_PASSWORD=$GF_PW

# Provider API keys are encrypted at rest with AES-256-GCM when this is set.
MEMORY_OS_MASTER_KEY=$MASTER_KEY

# Sign JWTs. Keep this stable; rotating it invalidates all existing sessions.
MEMORY_OS_JWT_SECRET=$JWT_SECRET

# Public domain — informational; nginx config is separate.
PUBLIC_DOMAIN=${DOMAIN:-}
EOF
  chmod 600 .env
  echo "  .env written (mode 600)"
fi

# ---- 3. bring up the stack -------------------------------------------------
echo "[3/5] docker compose up -d --build"
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

# ---- 4. wait for backend ---------------------------------------------------
echo "[4/5] Waiting for backend /health on :8003"
for i in $(seq 1 60); do
  code=$(curl -fs -o /dev/null -w '%{http_code}' --max-time 2 http://127.0.0.1:8003/health || true)
  if [[ "$code" == "200" ]]; then
    echo "  backend healthy after ${i}s"
    break
  fi
  sleep 1
  [[ $i -eq 60 ]] && { echo "  ERROR: backend did not become healthy within 60s"; docker compose logs --tail=80 backend; exit 1; }
done

# ---- 5. summary ------------------------------------------------------------
echo "[5/5] Done"
echo
echo "Backend listening on 127.0.0.1:8003 (not exposed to public — front it with nginx)"
echo "Default admin account:  admin / admin   (CHANGE THIS NOW via /manage/)"
echo
echo "Next steps:"
echo "  1. Install nginx + certbot and use config/nginx.conf as a template."
echo "  2. Open https://\${YOUR_DOMAIN}/manage/ and change the admin password."
echo "  3. See DEPLOY.md for the full SOP (firewall, backups, log rotation)."
